word=input("Please enter a word: ")
word=word.lower()
neword=" ".join(word)
print(neword)
neword=neword.replace("a","_")
neword=neword.replace("b","_")
neword=neword.replace("c","_")
neword=neword.replace("d","_")
neword=neword.replace("e","_")
neword=neword.replace("f","_")
neword=neword.replace("g","_")
neword=neword.replace("h","_")
neword=neword.replace("i","_")
neword=neword.replace("j","_")
neword=neword.replace("k","_")
neword=neword.replace("l","_")
neword=neword.replace("m","_")
neword=neword.replace("n","_")
neword=neword.replace("o","_")
neword=neword.replace("p","_")
neword=neword.replace("q","_")
neword=neword.replace("r","_")
neword=neword.replace("s","_")
neword=neword.replace("t","_")
neword=neword.replace("u","_")
neword=neword.replace("v","_")
neword=neword.replace("w","_")
neword=neword.replace("x","_")
neword=neword.replace("y","_")
neword=neword.replace("z","_")
print(neword)

